# Generated by Django 2.0.2 on 2018-03-06 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appusersmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusersmodel',
            name='date_joined',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='appusersmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='appusersmodel',
            name='last_login',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='appusersmodel',
            name='username',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
