# Generated by Django 2.0.2 on 2018-03-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180306_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusersmodel',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
