# Generated by Django 2.0.2 on 2018-03-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180306_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStops',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('user_id', models.IntegerField(max_length=11)),
            ],
        ),
    ]
