# Generated by Django 2.0.2 on 2018-03-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_appstops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appstops',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
