# Generated by Django 2.0.2 on 2018-03-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180306_0943'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppStops',
            new_name='AppStopsModel',
        ),
    ]
